# Name of this GitHub Actions workflow.
name: Semgrep SCA Scan of Branch

on:
  # Scan on-demand through GitHub Actions interface:
  workflow_dispatch: {}
jobs:
  semgrep:
    name: semgrep/ci 
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep

    if: (github.actor != 'dependabot[bot]')

    steps:
      - uses: actions/checkout@v3
      - run: |
          semgrep ci --supply-chain
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
          SEMGREP_REPO_NAME: "${GITHUB_REPOSITORY}/${GITHUB_REF#refs/heads/}"
